server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;

  # serve static files
  location / {
    try_files $uri $uri/ /index.html;
  }

  # gzip optional
  gzip on;
  gzip_types text/plain application/javascript text/css application/json;
}
